name: BuildPlugin
author: ByteList
version: mvn:unknown
#description
main: de.gamechest.buildplugin.BuildPlugin

loadbefore: [WorldEdit]

commands:
   gamemode:
      aliases: [gm]
   gamemap:
   speed:
   buildmode:
   buildconnect:
   loadschematic:
     aliases: [loadsch]
   blockinfo:
